# Generated by Django 5.0.2 on 2024-02-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_location', models.CharField(max_length=50)),
                ('company_about', models.TextField()),
                ('company_types', models.CharField(choices=[('IT', 'IT'), ('NON IT', 'NON IT'), ('Mechanical', 'Mechanical')], max_length=50)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('company_active', models.BooleanField(default=True)),
            ],
        ),
    ]
