# Generated by Django 5.0.2 on 2024-02-22 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_first_name', models.CharField(max_length=30)),
                ('employee_last_name', models.CharField(max_length=30)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('employee_phone', models.CharField(max_length=20)),
                ('employee_position', models.CharField(choices=[('software dev', 'software dev'), ('manager', 'manager'), ('junior associate', 'junior associate')], max_length=50)),
                ('employee_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('employee_date_of_birth', models.DateField()),
                ('employee_address', models.CharField(max_length=150)),
                ('employee_city', models.CharField(max_length=30)),
                ('employee_country', models.CharField(max_length=30)),
                ('employee_postal_code', models.CharField(max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
